### ISSUE TITLE
Resolved issue in profile.js

### ISSUE THREAD

**Issue by tammai** [Elijbet/Goodreads_clone#1]
Good morning, Liz!
You can get the working file here. Below are what I'd found and solved:
- Commit **'SET_MYLIST'** outside of Promise.then() (as you known).
- Firebase will return nothing if you save an empty array, so you will get error when filter an **undefined** array.
- Firebase will return **null** if you save an empty object, so you will get error when save an empty object then load it after that.
- User can choose the **'Choose...'** option in dropdown, you also get an error when add book to an **'undefined'** list.
- And last but not least, never compare 2 objects but compare any unique values inside these objects, like **id** or **ISBN**

Hope this help.

[profile.js.zip](https://github.com/Elijbet/Goodreads_clone/files/1610765/profile.js.zip)

**Comment by Elijbet** [comment]
I'll make the changes. Thanks, this really helps!
